### ISSUE TITLE
DAIA Applications

### ISSUE THREAD

**Issue by lahmann** [jakobib/daia2016#1]
Just stumbled upon this and would like to add VuFind's DAIA capabilities (active development of the DAIA driver) and we (finc) are also currently developing DAIA services for ILSes such as Bibliotheca and Libero:
- https://github.com/finc/DaiaTheca
- https://github.com/finc/DaiaLibero

**Comment by nichtich** [comment]
Thanks! I added the information in this section https://github.com/jakobib/daia2016/blob/master/finding-availability.md#daia-servers Further suggestions are welcome!
